spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${DATA_BASE}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      idle-timeout: 60000
      connection-timeout: 30000
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: reinaldo.holtz@gmail.com
    password: birh tljr urmm gcer
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true